LnkShortcut: check format error
[cuckoo.core.plugins] ERROR: Failed to run the processing module "Static" for task #642855:
Traceback (most recent call last):
  File "cuckoo/cuckoo/core/plugins.py", line 243, in process
    data = current.run()
  File "cuckoo/cuckoo/processing/static.py", line 1103, in run
    static["lnk"] = LnkShortcut(f.file_path).run()
  File "cuckoo/cuckoo/processing/static.py", line 811, in run
    off = LnkEntry.from_buffer_copy(buf[offset:offset + 28])
ValueError: Buffer size too small (0 instead of at least 28 bytes)