avoid socketserver traceback upon termination of cuckoo
Without this patch we'd sometimes get the following traceback.
Presumably the "select" module is unloaded and therefore set to
None while the SocketServer is still attempting to operate it.

Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/usr/lib/python2.7/SocketServer.py", line 235, in serve_forever
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'select'